# Generated by Django 5.0.2 on 2024-02-27 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('plant_photo', models.ImageField(default='images/plant_default.jpg', upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('rarity_id', models.AutoField(primary_key=True, serialize=False)),
                ('rarity_desc', models.CharField(max_length=10)),
                ('rarity_points', models.IntegerField()),
                ('rarity_colour', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainability.plant')),
                ('rarity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainability.rarity')),
            ],
        ),
        migrations.CreateModel(
            name='PlantOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainability.card')),
            ],
        ),
        migrations.CreateModel(
            name='UsersCard',
            fields=[
                ('users_cards_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainability.card')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
