# Generated by Django 5.0.2 on 2024-02-23 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainability', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('rarity_id', models.AutoField(primary_key=True, serialize=False)),
                ('rarity_desc', models.CharField(max_length=10)),
                ('rarity_points', models.IntegerField()),
                ('rarity_colour', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_photo',
            field=models.ImageField(default='static/images/plant_default.jpg', upload_to='static/images'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainability.plant')),
                ('rarity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainability.rarity')),
            ],
        ),
        migrations.CreateModel(
            name='UsersCard',
            fields=[
                ('users_cards_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainability.card')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
