# Generated by Django 5.0.2 on 2024-03-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainability', '0002_leaderboard_leaderboard_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
