# Generated by Django 5.0.2 on 2024-02-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainability', '0002_rarity_plant_plant_photo_card_userscard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plant_photo',
            field=models.ImageField(default='images/plant_default.jpg', upload_to='images'),
        ),
    ]
