# Generated by Django 5.0.2 on 2024-02-25 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainability', '0004_alter_plant_plant_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantoftheday',
            options={'permissions': [('add_plant_of_the_day', 'Can add plant of the day')]},
        ),
        migrations.AlterField(
            model_name='plantoftheday',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainability.card'),
        ),
    ]
