# Generated by Django 5.0.2 on 2024-03-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainability', '0004_rename_public_leaderboard_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMasterCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
