# Generated by Django 5.0.2 on 2024-02-25 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainability', '0005_alter_plantoftheday_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantoftheday',
            options={},
        ),
    ]
